### ISSUE TITLE
Choose a certain day for reminder

### ISSUE THREAD

**Issue by paulle** [felixwiemuth/SimpleReminder#10]
Please check the list of planned features in README.md first.
Please can you add the possibility to choose a certain date for the reminder not only the time.

**Comment by felixwiemuth** [comment]
Hi @paulle, the hint to check the list of planned features meant that it is not necessary to make feature requests for already planned features ;).

However, I plan to add issues for features that will be coming soon, so that there can be a discussion.
In addition there will be a channel on Matrix where people can informally discuss about the project.

**Comment by felixwiemuth** [comment]
## Plan for a design
My current plan for how one will be able to choose the date is the following:

- Above (or below) the clock the currently chosen date (by default today) is displayed with decrement/increment buttons to the left and right.
- Clicking on the date opens a calendar where one can choose a specific date directly.

### Dealing with times within the next 24 hours
As one should of course still be able to choose a time within the next 24 hours without having to use the date picker, choosing a time that is before the current time will continue to be assumed to be at the next day. In that case I think it would also be of benefit if the date chosen this way is displayed directly when updating the time on the clock. There is a little conflict when being able to choose the date in these two ways. For instance, what should happen when the chosen day is tomorrow because of the selected time and one manually wants to decrement to today? This would result in a reminder time in the past, which should not be possible. Disallowing to decrement the date in this case would mean that one has to choose the time first and then the day, which is not nice either.

I am thinking of solving this in the following way:
- There are two modes, a "next 24 hours" mode where the date is set automatically and a "manual date" mode where the date is explicitly set with the increment/decrement buttons or the calendar.
- In addition to the resulting date, a "+x" is displayed, where x is the number of days this date is ahead. The color of this serves as a mode indicator (see below) but I think it is also useful in general so that one doesn't lose track of how many days ahead one selected.

#### Behaviour in the two modes and switching modes
- Initially, the "next 24 hours" mode is activated, indicated by the color of the initial "+0". Just using the clock to select a time does not change the mode but the date will update between +0 and +1 depending on the selected time.
- The first time one manually selects a date different from the current one (by increment button or calendar), the mode is switched to "manual date", now indicated by a different color of the "+x". In this mode, changing the time with the clock will not update the date (which will always be at least "tomorrow").
- Note that usually one would switch to "manual date" mode before selecting the time (as first selecting date and then time seems like a more natural flow), so the mode switch would usually happen by changing +0 to +1 with the increment button (or to +x with the calendar). However, it is of course possible to change the date after changing the time and thus potentially already having selected a +1 date. In this case, using the increment button will not further increment the date but only switch to "manual date" mode. This "unlocks" choosing times at that day that are 24 hours or more ahead (in "next 24 hours" mode this would switch back to +0). Selecting the next day in the calendar will also change the mode, even though the date is the same.
- Switching back to "next 24 hours" mode from "manual date" mode either happens by choosing the current date in the calendar or with the decrement button when the date selection is at +1. In either case, depending on whether the selected time is on the current day or the next day, this will switch the date to +0 or +1 (which now again updates automatically).

**Comment by kiedan** [comment]
Adding a date is the thing I am missing most so far. The way you plan implementing it sounds great, looking forward to it!

**Comment by felixwiemuth** [comment]
Good news! This feature is now implemented and already being tested to see that everything works as expected.

There are only a few minor changes to the description above:
- "+0" is not displayed, this makes the difference between +0 and +x even more clear (because when the +1 appears, the centered text with the date shifts a bit).
- The mode is indicated by the whole date text being colored orange for manual mode, and the +1 being colored blue in "next 24 hours" mode.
- Choosing a date in the calendar that with the selected time is within the next 24 hours results in switching to "next 24 hour" mode.
- When exactly the mode is switched, and when it is possible to use the "+" and "-" buttons and the calendar and what the behaviour of these inputs is is quite complex (there are many different cases), but I think I have found a good solution which should be intuitive to use.

**Comment by tiritibambix** [comment]
Any release date for this feature ? :)

**Comment by felixwiemuth** [comment]
After a bit of testing and trying out different variants, I have made a small change regarding the mode switching behaviour described above, which results in a quite simple rule:

Any use of the "+/-" buttons or the calendar to select a date leads to "manual date" mode, except if one attempts to choose the current day, in which case one will always land in "next 24 hour" mode. This means that the actually selected date can be the next day ("+1"). However, also in that case the "next 24 hour" mode will allow to choose any valid time on the current day (i.e., the day one originally wanted to choose) by simply changing the time. That is, the workflow of choosing the current day (after having chosen another day first) with the "-" button or the calendar and then a time on the current day is supported.

**Comment by felixwiemuth** [comment]
Now version 0.9.10 is eventually released and this feature is available!

Please test and give feedback :)

**Comment by yephny** [comment]
It's great, I love it!
