### ISSUE TITLE
Urgent – or nagging – reminder

### ISSUE THREAD

**Issue by sphh** [felixwiemuth/SimpleReminder#2]
Just an idea: Some reminders have a very high urgency and it is easy to miss them. An urgent reminder would either sound the alarm until silenced or would repeat the alarm in a set interval (e.g. every minute) until acknowledged …

**Comment by felixwiemuth** [comment]
Hi @sphh, the main solution for differentiating between more and less important reminders will be the use of notification channels (already listed in Readme).

The idea is that you can configure different notification modes (channels) yourself and then select one of those when adding a reminder. From Android 8 on, one can configure notification channels under "app info", i.e., outside the app, in a system wide uniform way. You might have seen some newer apps doing it this way.

While with this approach one can have notifications with sound, vibration, etc. (even choosing to ignore "do not disturb"), there is still a difference to an alarm as you describe it. I think a real alarm like the usual/default alarm apps provide (alarms that sound until turned off or snoozed) would still be a useful feature in SimpleReminder, as it will allow for an easier scheduling of one-time or occasional alarms than when using an alarm app (which are rather made for recurring alarms that you can turn on and off).

A first idea on how to realize this would be to introduce a new type of reminder ("alarm"). Instead of showing a notification, this type could show an "alarm screen" as known from alarm apps, where one has the options to turn off, snooze etc. Here one could also allow the user to define different alarm setups (sound, repetition, increasing volume, vibration, snooze options ...) in the settings, that can then be selected when adding a reminder.

I think the feature of multiple notification channels will be limited to Android 8+, and pre Android 8 devices will only be able to configure notifications globally under settings, applying to all reminders as it is now. However, the "alarm type" reminder could be available on all versions.

**Comment by sphh** [comment]
Yes, I had the "alarm type" as described by you in mind. Personally I don't consider the different notification channels useful, because I set the reminder deliberately and then I actually want to be notified. I think this this is different from notifications from email/messenger apps, which can become quite annoying … (Just my private opinion)

**Comment by felixwiemuth** [comment]
Hi again, I have thought a bit more about nagging reminders and came up with a solution which would also be not too complex to implement.

In addition to alarms (which will be a bit more advanced to implement) and different notification channels for notification-based reminders, there could be a new type "nagging reminder" which is like a normal notification reminder, but where the notification simply is renewed every x minutes (configurable when adding the reminder) until dismissed. Each time the notification is repeated this way, the same sound, vibration etc. would occur depending on the notification channel settings.

This type of reminder will especially help when one misses the the first notification, or forgets about it again. One also does not have to reschedule a reminder just to delay it a bit (this will be easier in the future with controls and actions from the notification, but one would still have to do it).

I think this would be a good middle-way in comparison to alarms, which sound continuously until snoozed or dismissed. Of course also alarms could have options to play only for a certain time and repeat by a pattern, resulting in a similar alert. But with alarms having an alarm screen and priorities like normal alarms, they could represent reminders of the highest importance, whereas nagging notifications (with notification typical one-time alerts, but repeated) would represent reminders of middle importance and normal notifications reminders of low importance.

The nice thing is that both notification-based reminder types can further be configured via notification channels (for now just one, but in future multiple), so independent of whether it is nagging or not, one can set sound, vibration etc. An advanced feature for nagging reminders could be that they would change the notification channel after the first reminder (e.g. to make it more intrusive by adding sound).

**Comment by sphh** [comment]
That sounds perfect!!

**Comment by kiedan** [comment]
I also would love to see that feature. I have a great talent to dismiss or forget important reminders (like: "ah yeah that reminder, let me just quickly finish that other thing ...") If I could simply tap on an additional icon when creating a reminder to mark it as urgent/nagging and then have it automatically come back every few minutes, that would definiately be awesome!

**Comment by felixwiemuth** [comment]
I am now working on a first version of nagging reminders (scheduled for the next release).

- There will be an on/off toggle in the "Add Reminder" dialog to enable nagging reminders.
- The repeat interval for the notifications can be set globally in the settings (in minutes) and be changed just for the current reminder by long-pressing the switch.
- There won't be any indication yet in the reminders list or the notification whether the reminder is nagging (and if so with what repeat interval). But when editing the reminder one can see whether the switch is turned on and see the repeat interval by long-pressing the switch.

**Comment by felixwiemuth** [comment]
I am happy to announce that nagging reminders in the described first version are now implemented and available in release 0.9.9 :).

**Comment by sphh** [comment]
Thanks!!!
