### ISSUE TITLE
Cropout action bar

### ISSUE THREAD

**Issue by tuekacode** [felixwiemuth/SimpleReminder#4]
![20210215_150715](https://user-images.githubusercontent.com/77476143/107915475-83ffe180-6f9f-11eb-9961-9511d6e31f0d.jpg)
When im trying to remove the reminder list, the menu bar got cropped out

**Comment by rusty-electron** [comment]
I am experiencing this issue too.

**Comment by felixwiemuth** [comment]
Thanks for reporting this, it is strange that it seems to occur only on a few devices.

For those experiencing this, can you give me some more information? For example:
- Which Android version and which phone model do you use?
- Does it always happen when selecting a reminder or just sometimes?
- Is there a difference when first having scrolled the reminders list fully up or fully down? This could be relevant because the "SimpleReminder" bar should vanish under the status bar when one scrolls down and maybe this makes a difference.

**Comment by felixwiemuth** [comment]
The new version 0.9.11 contains several updates of UI libraries, maybe this solves the problem. Otherwise please reopen.
