### ISSUE TITLE
Hide the keyboard when using the time selector

### ISSUE THREAD

**Issue by 82MHz** [felixwiemuth/SimpleReminder#44]
This is a minor quirck of the app, but one that's still throwing me off every time I encounter it:

After I added the text of a reminder and want to use the time selector to set the alarm time, the android keyboard stays open, blocking half of the time selector. I have to manually click the keyboard away every time.

It seems this is happening because even when using the time selector, the text input field stays active and so android leaves the keyboard open.

I'm wondering if it is possible to take focus away from the text input field when an input is made to the time selector so that android hides the keyboard? It would greatly improve the usability of the app IMO.

**Comment by felixwiemuth** [comment]
Hi, thanks for sharing the observation!

This is only relevant when the time picker is so much hidden by the keyboard that you can't use it well. I think that on most devices this actually does not happen, but it might be more often than I thought.

It should be relatively easy to fix, I'll take a look when I find the time.

However, I would implement it as an option for small screens / large keyboards, because if both keyboard and time picker can fit on the screen at the same time, it is actually an advantage that the text field keeps the focus and the keyboard stays open, because you can freely switch between selecting time and entering text.

**Comment by 82MHz** [comment]
Hi, thanks for the response! 

I agree, when everything fits on the same screen, it's a good solution. 

I have a Samsung Galaxy S10e which is relatively small for a modern smartphone, and the interface looks like the screenshot below, so having the option to have the keyboard disappear as soon as I start dialing in the time would be perfect for me :)

![Screenshot_20230927-115709_SimpleReminder](https://github.com/felixwiemuth/SimpleReminder/assets/16221316/5bb3b0cf-c386-40a6-9d06-69ffcee8d177)

**Comment by felixwiemuth** [comment]
There is now a new option to enable this behaviour in version 0.9.13 (just released).

Currently closing the keyboard results in the "Add reminder" screen changing its position on the screen, which could be a bit annoying when just having touched the clock, because it moves away a bit and one has to follow it. I might at some point look into whether it is possible to keep the position of the "Add reminder" screen. Then this could be an option to enable in connection with this feature.

**Comment by 82MHz** [comment]
I updated the app right away yesterday, it works perfectly! 

Thank you very much for implementing! It makes the app a lot more user friendly in my opinion :)
