### ISSUE TITLE
Resizing reminder dialog doesn't work (Android 5.1.1)

### ISSUE THREAD

**Issue by a-pav** [felixwiemuth/SimpleReminder#48]
I resized the reminder dialog to values below the default ones but I didn't see any changes applied.
I enabled/disabled "Apply custom sizes set below" option, completely closed the app and restarted it, and yet it didn't work.

- App version: 0.9.13
- Android version: 5.1.1

<sub>Enabling "Close keyboard when using clock" option hides the keyboard but also makes the time picker frozen, unresponsive to touch</sub>

**Comment by felixwiemuth** [comment]
Thanks for the report!

I just tested it on different Android versions in the emulator and it seems that in old Android versions (e.g. also 7.0) it doesn't work. I'll find out from which version it works and whether it is easy to fix for older versions.

The last part of your post, could you report that as a separate bug with more details? Thanks.

**Comment by felixwiemuth** [comment]
The emulator comes with Android Studio, more info here: https://developer.android.com/studio/run/emulator

**Comment by felixwiemuth** [comment]
I discovered that due to a layout change of the time picker in Android 8, the code for customizing the sizes did not find the relevant parts in earlier Android versions. This is now fixed in version 0.9.14, and changing sizes works on all Android versions down to Android 5.0 (first version which comes with a clock widget for the time picker; on Android below version 5, the setting is now not shown anymore).

Note that scaling the clock on Android 5 doesn't look that good, as the time picker has a different layout than the one used frow Android 6, and I currently won't prioritize improving that. PRs are welcome though.
