### ISSUE TITLE
Setting for minute intervals

### ISSUE THREAD

**Issue by alastajj** [felixwiemuth/SimpleReminder#9]
I found that it can take a while to scroll the minutes wheel to get to the time you want. 

Perhaps if you could change a setting so that the minutes was only shown in intervals of 5 minutes? Would make it more efficient for setting reminders at the desire time. (e.g. 0,5,10,15,20 etc. instead of 1,2,3,4,5,6,7 etc.) I realized that when I've used google's reminders in the past, the exact minute time was rarely needed, I tended to use whole numbers like "6pm" or "7:30", I don't usually need to do "7:34pm".

 Thank you very much for this program, looking forward to setting the day/date as well.

**Comment by felixwiemuth** [comment]
Yes I fully agree, and I think it will be most common to not care about further divisions within 5 minute intervals.

For now, however, I am thinking of replacing the current time picker (spinner variant) with the default clock variant. It will generally be more efficient, assuming that one does not care so much about minutes. In addition (since some Android version) this variant also has a mode to type the time, which I do not find optimal but it doesn't hurt to have it for now.

Another reason to at least temporarily go away from the current time picker is that when typing the time with the keyboard and then clicking "Add" before clicking "OK" on the keyboard, the typed time is not saved.

Note that the clock variant is only available on Android 5.0 and above, older versions will continue to use the spinner.

When it comes to choosing time relatively (e.g. *in* 5, 10, ... minutes), the spinner and a configurable stepping will become relevant again. See also the discussion under #1 on this.

P.S. Which Google reminders were you referring to?

**Comment by felixwiemuth** [comment]
As suggested above, in the just released version 0.9.7 the "spinner" time picker has now been replaced with the default "clock" time picker.

So for now the problem is solved and when there will be spinners or similar pickers again, the efficiency in selecting the desired value will of course be considered.

For further discussion on time input refer to #1.
